name: Java CI
on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java_version: [11, 14]
        os: [ubuntu-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java_version }}
        distribution: 'zulu'
    - name: Print Java and Maven versions
      run: ./mvnw -B -s .github/settings.xml -v
    - name: Build with Maven
      run: ./mvnw -B -s .github/settings.xml install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true
    - name: Run tests
      run: ./mvnw -B -s .github/settings.xml verify
